apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nextjs
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextjs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nextjs
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mysql://admin:admin@mysql:3306/default_db
            - name: NEXT_PUBLIC_API_URL
              value: http://localhost:3000/api
          image: nextjs
          name: nextjs
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: nextjs-cm0
            - mountPath: /app/node_modules
              name: nextjs-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: nextjs-cm0
          name: nextjs-cm0
        - name: nextjs-claim1
          persistentVolumeClaim:
            claimName: nextjs-claim1
